name: Test Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Pull Docker image 
      run: docker pull quay.io/tembo/pgmq-pg:latest
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build and run tests
      run: dotnet test
